"""bater metadata module."""
__name__ = "bater"
__description__ = "Battery manager."
__version__ = "0.0.0"
__author__ = "myslak71"
__author_email__ = "myslak@protonmail.com"
__url__ = ""
__license__ = "MIT"
__copyright__ = "Copyright 2019 myslak71"
__keywords__ = "battery"
__download_url__ = ""
